{% set name = "misic-napari" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/misic-napari-{{ version }}.tar.gz
  sha256: 622283bfbcdd1c64396b61224a3d35e31c73839b04de5a71caf0d1815ca6e136

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - napari
    - napari-plugin-engine
    - python >=3.6
    - tensorflow >=2
    - scikit-image

test:
  imports:
    - misic_ui
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pswapnesh/MiSiC
  summary: Segmentation of bacteria agnostic to imaging modality
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
